version: '3'
services:
  mysolr:
    image: "solr:8"
    ports:
     - "8983:8983"
    command:
      - solr-precreate
      - gettingstarted
  proxy:
    image: nginx
    ports:
    - 8899:80
    volumes:
    - ./nginx-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
